### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by YangXu-Insist** [SailorTheMan/lidar_test#1]
Hello ! Can this enable autonomous navigation by untree a1?

**Comment by SailorTheMan** [comment]
Hello. This packet was tested on unitree a1 with external jetson xavier that communicate with robot via unitree sdk. By the way, we used older version of unitree sdk that supports unitree a1.

**Comment by YangXu-Insist** [comment]
> Hello. This packet was tested on unitree a1 with external jetson xavier that communicate with robot via unitree sdk. By the way, we used older version of unitree sdk that supports unitree a1.

I'm very glad you can reply to me! I am also studying UnitreeA1 recently, but that is a raspberry pi instead of jetson xavier, so I want to add an external jetson xavier and use it for velodyne16 for slam, can you provide some suggestions ？Thank you very much !!!
![image](https://user-images.githubusercontent.com/58600456/141689416-6a8aed75-50ef-4ab1-a503-07b65c35ea0b.png)
![image](https://user-images.githubusercontent.com/58600456/141689574-973f2e00-4d7d-4e28-b022-d8bc3535e1bc.png)

**Comment by QuoZer** [comment]
Our work was focused mainly on getting this to work with a Realsense depth camera, so you'll have to do the LIDAR-related part yourself. Apart from that it's pretty functional - receives all the data (including odometry) from the robot, controls movement based on /cmd_vel messages and ties it all together with RTABMAP. 
We were using an external Jetson Xavier as well, so it's OK, you can use the ARM branch of our repository. In order to make it work, you'll just need to edit our launch files to accept laser scan from Velodyne (instead of the one generated from depth image) and update static TF to match your sensor location. 
I hope it helps, We will be happy to see your results in case our code will be of any use.
